Repository lgdlong/g3-swp391-2hand-ev-battery-trading, pull requests merged in 2025-10, with the labels that each got.

#41 làm trang profile, chỉnh sửa profile đã nối api và làm trang home, cả…
  apps/api/src/modules/posts/posts.service.ts
  apps/db/dump-2hand_ev_battery_trading-202509291411.dump
  apps/web/app/(auth)/login/page.tsx
  apps/web/app/(auth)/sign-up/page.tsx
  apps/web/app/(public)/layout.tsx
  apps/web/app/(public)/posts/battery/[id]/page.tsx
  apps/web/app/(public)/posts/battery/page.tsx
  apps/web/app/(public)/posts/create/page.tsx
  apps/web/app/(public)/posts/ev/[id]/_components/SellerInfo.tsx
  apps/web/app/(public)/posts/ev/[id]/_components/SpecItem.tsx
  apps/web/app/(public)/posts/ev/[id]/_components/Specifications.tsx
  apps/web/app/(public)/posts/ev/[id]/_components/index.ts
  apps/web/app/(public)/posts/ev/[id]/page.tsx
  apps/web/app/(public)/posts/ev/_queries.ts
  apps/web/app/(public)/posts/ev/layout.tsx
  apps/web/app/(public)/posts/ev/page.tsx
  apps/web/app/(public)/posts/ev/sample-ev.ts
  apps/web/app/(public)/posts/layout.tsx
  apps/web/app/(public)/profile/layout.tsx
  apps/web/app/(public)/profile/page.tsx
  apps/web/app/globals.css
  apps/web/app/layout.tsx
  apps/web/app/page.tsx
  apps/web/components/asset/phu-tung-o-to-27.png
  apps/web/components/navbar/UserSidebar.tsx
  apps/web/components/navbar/index.ts
  apps/web/components/navbar/navbar.tsx
  apps/web/components/searchbar/searchbar.tsx
  apps/web/components/ui/button.tsx
  apps/web/lib/adapters/account.ts
  apps/web/lib/adapters/post.ts
  apps/web/lib/api/accountApi.ts
  apps/web/lib/api/index.ts
  apps/web/lib/api/postApi.ts
  apps/web/lib/auth-context.tsx
  apps/web/lib/auth-manager.ts
  apps/web/lib/axios.ts
  apps/web/lib/utils/format.ts
  apps/web/next.config.js
  apps/web/public/asset/phu-tung-o-to-27.png
  apps/web/types/account.ts
  apps/web/types/post.ts
Labels: Possible security concern, Review effort 4/5

#57 Style/split-components-ev-page
  apps/web/app/(public)/posts/ev/[id]/page.tsx
  apps/web/app/(public)/posts/ev/_components/EmptyState.tsx
  apps/web/app/(public)/posts/ev/_components/LoadingGrid.tsx
  apps/web/app/(public)/posts/ev/_components/PageHeader.tsx
  apps/web/app/(public)/posts/ev/_components/PostCard.tsx
  apps/web/app/(public)/posts/ev/_components/PostGrid.tsx
  apps/web/app/(public)/posts/ev/_components/index.ts
  apps/web/app/(public)/posts/ev/_components/types.ts
  apps/web/app/(public)/posts/ev/_components/utils.ts
  apps/web/app/(public)/posts/ev/page.tsx
Labels: Review effort 2/5

#59 Feat/frontend/bookmark-button
  apps/web/app/(public)/posts/battery/page.tsx
  apps/web/app/(public)/posts/ev/[id]/page.tsx
  apps/web/app/(public)/posts/ev/_components/BookMarkButton.tsx
  apps/web/app/(public)/posts/ev/_components/HeartToggle.tsx
  apps/web/app/(public)/posts/ev/_components/PostCard.tsx
  apps/web/app/(public)/posts/ev/_components/PostGrid.tsx
  apps/web/components/navbar/navbar.tsx
  apps/web/lib/utils/format.ts
Labels: Review effort 2/5

#62 feat: add AI code review workflow and scripts for issue creation and PR comments
  .github/workflows/ai-review.yml
  scripts/create_issues.js
  scripts/post_comment.js
  scripts/review.js
Labels: Review effort 3/5

#109 Feat/upload avatar
  ai-prompt/lgdlong/pr-109/SECURITY.md
  ai-prompt/lgdlong/pr-109/SECURITY_RESOLUTION.md
  ai-prompt/lgdlong/pr-109/issues-pr-109.md
  ai-prompt/lgdlong/upload-avatar.md
  apps/web/app/(public)/profile/_components/AvatarChangeDialog.tsx
  apps/web/app/(public)/profile/page.tsx
  apps/web/components/navbar/UserActions.tsx
  apps/web/components/navbar/UserSidebar.tsx
  apps/web/components/navbar/navbar.tsx
  apps/web/components/ui/avatar.tsx
  apps/web/components/ui/dialog.tsx
  apps/web/config/constants.ts
  apps/web/hooks/.gitkeep
  apps/web/hooks/useUploadAvatar.ts
  apps/web/lib/api/accountApi.ts
  apps/web/lib/auth-context.tsx
  apps/web/lib/validation/file-validation.ts
  apps/web/next.config.js
  apps/web/package.json
  pnpm-lock.yaml
Labels: Review effort 3/5

#125 fix: add account status check to prevent login for banned users
  apps/api/src/modules/auth/auth.module.ts
  apps/api/src/modules/auth/auth.service.ts
Labels: Review effort 2/5

#166 feat: fix admin/posts
  .github/workflows/ci.yml
  .husky/pre-commit
  README.md
  apps/api/src/modules/posts/posts.controller.ts
  apps/api/src/modules/posts/posts.service.ts
  apps/web/app/(dashboard)/admin/posts/page.tsx
  apps/web/app/(public)/posts/create/_components/EVDetailsForm.tsx
  apps/web/app/(public)/posts/create/_hooks/useCreatePost.ts
  apps/web/app/(public)/posts/ev/_components/PostCard.tsx
  apps/web/app/(public)/posts/ev/_components/PostGrid.tsx
  apps/web/app/(public)/posts/ev/_components/index.ts
  apps/web/app/(public)/posts/ev/_components/types.ts
  apps/web/app/(public)/posts/ev/_components/utils.ts
  apps/web/app/(public)/posts/ev/page.tsx
  apps/web/app/page.tsx
  apps/web/lib/api/postApi.ts
  apps/web/types/api/post.ts
  apps/web/types/post.ts
  package.json
Labels: Review effort 3/5

#173 Feat/frontend/active-range-filter
  apps/web/app/(public)/posts/battery/[id]/page.tsx
  apps/web/app/(public)/posts/battery/page.tsx
  apps/web/app/(public)/posts/battery/sample-battery.ts
  apps/web/app/(public)/posts/ev/[id]/page.tsx
  apps/web/app/(public)/posts/ev/page.tsx
  apps/web/components/breadcrumb-filter/BatteryBrandFilterDropdown.tsx
  apps/web/components/breadcrumb-filter/BatteryFilters.tsx
  apps/web/components/breadcrumb-filter/BrandFilterDropdown.tsx
  apps/web/components/breadcrumb-filter/BreadcrumbFilter.tsx
  apps/web/components/breadcrumb-filter/CapacityFilterDropdown.tsx
  apps/web/components/breadcrumb-filter/CyclesFilterDropdown.tsx
  apps/web/components/breadcrumb-filter/EvFilters.tsx
  apps/web/components/breadcrumb-filter/FilterButton.tsx
  apps/web/components/breadcrumb-filter/FilterButtons.tsx
  apps/web/components/breadcrumb-filter/HealthFilterDropdown.tsx
  apps/web/components/breadcrumb-filter/PriceFilterDropdown.tsx
  apps/web/components/breadcrumb-filter/RangeFilterDropdown.tsx
  apps/web/components/breadcrumb-filter/components/ButtonRenderer.tsx
  apps/web/components/breadcrumb-filter/components/DropdownButtons.tsx
  apps/web/components/breadcrumb-filter/components/DropdownManager.tsx
  apps/web/components/breadcrumb-filter/constants/dropdownConstants.ts
  apps/web/components/breadcrumb-filter/constants/filterConstants.ts
  apps/web/components/breadcrumb-filter/hooks/useFilterHandlers.ts
  apps/web/components/breadcrumb-filter/index.ts
  apps/web/components/breadcrumb-filter/types.ts
  apps/web/components/breadcrumb-filter/useBreadcrumb.ts
  apps/web/components/navbar/navbar.tsx
  apps/web/components/searchbar/BrandFilter.tsx
Labels: Review effort 3/5

#180 Feat/search-posts
  apps/api/src/modules/posts/posts.controller.ts
  apps/api/src/modules/posts/posts.service.ts
  apps/api/src/shared/constants/post.ts
  apps/web/app/(public)/posts/ev/page.tsx
  apps/web/components/searchbar/searchbar.tsx
  apps/web/lib/api/postApi.ts
Labels: Review effort 3/5
