Repository lgdlong/g3-swp391-2hand-ev-battery-trading, pull requests merged in 2025-09, with the labels that each got.

#8 feat/backend/api-login
  apps/api/package.json
  apps/api/src/app.module.ts
  apps/api/src/main.ts
  apps/api/src/modules/accounts/accounts.service.ts
  apps/api/src/modules/auth/auth.controller.ts
  apps/api/src/modules/auth/auth.module.ts
  apps/api/src/modules/auth/auth.service.ts
  apps/api/src/modules/auth/dto/login-request.dto.ts
  apps/api/src/modules/auth/interfaces/jwt-payload.interface.ts
  apps/api/src/modules/auth/interfaces/login-response.interface.ts
  apps/api/src/modules/auth/interfaces/tokens.interface.ts
  apps/api/src/modules/auth/local.strategy.ts
  apps/api/src/shared/constants/index.ts
  apps/api/src/shared/helpers/.gitkeep
  apps/api/src/shared/helpers/account.helper.ts
  pnpm-lock.yaml
Labels: Possible security concern, Review effort 4/5

#9 feat/login-email-phone
  apps/db/dump-2hand_ev_battery_trading-202509140021.dump
  apps/web/app/(auth)/login/page.tsx
  apps/web/app/(auth)/sign-up/page.tsx
  apps/web/app/layout.tsx
  apps/web/app/providers.tsx
  apps/web/components/FormRootError.tsx
  apps/web/components/login-form.tsx
  apps/web/lib/api/authApi.ts
  apps/web/lib/handle-api-error.ts
  apps/web/lib/query-client.ts
  apps/web/types/login.ts
  apps/web/validations/login-schema.ts
Labels: Possible security concern, Review effort 2/5

#15 14-backend-dont-show-password-at-register-response
  apps/api/src/modules/accounts/accounts.service.ts
  apps/api/src/modules/accounts/dto/create-account-response.dto.ts
  apps/api/src/modules/accounts/dto/summary-account.dto.ts
Labels: Possible security concern, Review effort 4/5

#18 docs: update README to include links to frontend, backend, and database documentation
  README.md
  ai-prompt/lgdlong/swagger-auth-accounts.md
Labels: documentation, Review effort 1/5

#22 chore(api): remove vehicle colors module and using enums just for more simple
  apps/api/src/modules/vehicle-colors/dto/create-vehicle-color.dto.ts
  apps/api/src/modules/vehicle-colors/dto/update-vehicle-color.dto.ts
  apps/api/src/modules/vehicle-colors/entities/vehicle-color.entity.ts
  apps/api/src/modules/vehicle-colors/vehicle-colors.controller.ts
  apps/api/src/modules/vehicle-colors/vehicle-colors.module.ts
  apps/api/src/modules/vehicle-colors/vehicle-colors.service.ts
  apps/api/src/shared/enums/vehicle-color.enum.ts
Labels: Review effort 2/5

#27 feat/backend/car-and-bike-catalog
  ai-prompt/lgdlong/structure-for-post-features.md
  ai-prompt/lgdlong/swagger-bike-catalog.md
  ai-prompt/lgdlong/swagger-car-catalog.md
  ai-prompt/lgdlong/swagger-create-car-bike-catalog-dto.md
  apps/api/src/app.module.ts
  apps/api/src/core/guards/roles.guard.ts
  apps/api/src/core/middleware/debug.middleware.ts
  apps/api/src/modules/accounts/accounts.controller.ts
  apps/api/src/modules/accounts/accounts.module.ts
  apps/api/src/modules/auth/auth.module.ts
  apps/api/src/modules/auth/auth.service.ts
  apps/api/src/modules/auth/interfaces/jwt-payload.interface.ts
  apps/api/src/modules/auth/jwt.strategy.ts
  apps/api/src/modules/catalogs/bikes/bike-catalog.controller.ts
  apps/api/src/modules/catalogs/bikes/bike-catalog.module.ts
  apps/api/src/modules/catalogs/bikes/bike-catalog.service.ts
  apps/api/src/modules/catalogs/bikes/bikes.controller.ts
  apps/api/src/modules/catalogs/bikes/bikes.module.ts
  apps/api/src/modules/catalogs/bikes/bikes.service.ts
  apps/api/src/modules/catalogs/bikes/dto/create-bike.dto.ts
  apps/api/src/modules/catalogs/bikes/dto/update-bike.dto.ts
  apps/api/src/modules/catalogs/bikes/entities/bike-brand.entity.ts
  apps/api/src/modules/catalogs/bikes/entities/bike-model.entity.ts
  apps/api/src/modules/catalogs/bikes/entities/bike-trim.entity.ts
  apps/api/src/modules/catalogs/cars/car-catalog.controller.ts
  apps/api/src/modules/catalogs/cars/car-catalog.module.ts
  apps/api/src/modules/catalogs/cars/car-catalog.service.ts
  apps/api/src/modules/catalogs/cars/cars.controller.ts
  apps/api/src/modules/catalogs/cars/cars.module.ts
  apps/api/src/modules/catalogs/cars/cars.service.ts
  apps/api/src/modules/catalogs/cars/dto/create-car.dto.ts
  apps/api/src/modules/catalogs/cars/dto/update-car.dto.ts
  apps/api/src/modules/catalogs/cars/entities/car-brand.entity.ts
  apps/api/src/modules/catalogs/cars/entities/car-model.entity.ts
  apps/api/src/modules/catalogs/cars/entities/car-trim.entity.ts
  apps/api/src/modules/catalogs/shared/dto/create-car-bike-catalog.dto.ts
  apps/api/src/modules/catalogs/shared/interfaces/lite-item.interface.ts
  apps/api/src/shared/dto/list-query.dto.ts
  apps/db/dump-2hand_ev_battery_trading-202509181454.dump
  apps/db/dump-2hand_ev_battery_trading-202509200414.dump
Labels: Review effort 3/5, Possible security concern

#32 fix/backend/remove-redundant-catalog-api
  apps/api/src/app.module.ts
  apps/api/src/core/decorators/user.decorator.ts
  apps/api/src/modules/accounts/entities/account.entity.ts
  apps/api/src/modules/catalogs/bikes/bike-catalog.controller.ts
  apps/api/src/modules/catalogs/bikes/bike-catalog.module.ts
  apps/api/src/modules/catalogs/bikes/bike-catalog.service.ts
  apps/api/src/modules/catalogs/bikes/entities/bike-model.entity.ts
  apps/api/src/modules/catalogs/bikes/entities/bike-trim.entity.ts
  apps/api/src/modules/catalogs/cars/car-catalog.controller.ts
  apps/api/src/modules/catalogs/cars/car-catalog.module.ts
  apps/api/src/modules/catalogs/cars/car-catalog.service.ts
  apps/api/src/modules/catalogs/cars/entities/car-model.entity.ts
  apps/api/src/modules/catalogs/cars/entities/car-trim.entity.ts
  apps/api/src/modules/posts/dto/create-post.dto.ts
  apps/api/src/modules/posts/entities/post.entity.ts
  apps/api/src/modules/posts/posts.controller.ts
  apps/api/src/modules/posts/posts.module.ts
  apps/api/src/modules/posts/posts.service.ts
  apps/api/src/shared/enums/post-status.enum.ts
  apps/api/src/shared/enums/post-type.enum.ts
Labels: Review effort 3/5

#31 feat(me): feat api /me profile GET and PATCH at account #26
  ai-prompt/thaiF15/me-api.md
  apps/api/src/core/decorators/current-user.decorator.ts
  apps/api/src/main.ts
  apps/api/src/modules/accounts/accounts.controller.ts
  apps/api/src/modules/accounts/accounts.service.ts
  apps/api/src/modules/accounts/dto/update-account.dto.ts
  apps/api/src/modules/auth/dto/login-request.dto.ts
Labels: Review effort 2/5

#43 Feat/google-login
  .github/copilot-instructions.md
  ai-prompt/lgdlong/edit-google-call-back-body.md
  ai-prompt/lgdlong/google-login.md
  apps/api/package.json
  apps/api/src/core/guards/google-oauth.guard.ts
  apps/api/src/modules/accounts/accounts.service.ts
  apps/api/src/modules/auth/auth.controller.ts
  apps/api/src/modules/auth/auth.module.ts
  apps/api/src/modules/auth/auth.service.ts
  apps/api/src/modules/auth/google.strategy.ts
  apps/api/src/modules/auth/interfaces/google-login-result.interface.ts
  apps/api/src/modules/auth/interfaces/google-profile.interface.ts
  apps/api/src/modules/auth/interfaces/raw-google-profile.interface.ts
  apps/api/src/shared/helpers/account.helper.ts
  apps/db/_sample_accounts.txt
  apps/web/app/(auth)/google-callback/GoogleCallbackBody.tsx
  apps/web/app/(auth)/google-callback/page.tsx
  apps/web/app/(auth)/login/page.tsx
  apps/web/lib/api/accountApi.ts
  apps/web/lib/api/authApi.ts
  apps/web/lib/auth-context.tsx
  pnpm-lock.yaml
Labels: Possible security concern, Review effort 4/5

#42 feat: add admin page
  apps/web/app/(auth)/login/page.tsx
  apps/web/app/(dashboard)/admin/accounts/page.tsx
  apps/web/app/(dashboard)/admin/layout.tsx
  apps/web/app/(dashboard)/admin/page.tsx
  apps/web/components/admin/AdminSidebar.tsx
  apps/web/lib/api/accountApi.ts
Labels: Review effort 3/5, Possible security concern

#47 refactor(navbar): update UserActions and UserSidebar components for improved UI and functionality
  apps/web/components/navbar/UserActions.tsx
  apps/web/components/navbar/UserSidebar.tsx
Labels: Review effort 2/5

#52 Feat/backend/upload-image
  ai-prompt/lgdlong/upload-cloudinary.md
  apps/api/package.json
  apps/api/src/app.module.ts
  apps/api/src/config/cloudinary.config.ts
  apps/api/src/core/interceptors/image-upload.interceptor.ts
  apps/api/src/modules/accounts/accounts.controller.ts
  apps/api/src/modules/accounts/accounts.module.ts
  apps/api/src/modules/accounts/accounts.service.ts
  apps/api/src/modules/accounts/entities/account.entity.ts
  apps/api/src/modules/posts/dto/base-create-post.dto.ts
  apps/api/src/modules/posts/dto/base-post-response.dto.ts
  apps/api/src/modules/posts/dto/create-media.dto.ts
  apps/api/src/modules/posts/dto/create-post-image.dto.ts
  apps/api/src/modules/posts/dto/post-image-response.dto.ts
  apps/api/src/modules/posts/entities/post-image.entity.ts
  apps/api/src/modules/posts/entities/post-media.entity.ts
  apps/api/src/modules/posts/entities/post.entity.ts
  apps/api/src/modules/posts/mappers/post-image.mapper.ts
  apps/api/src/modules/posts/mappers/post.mapper.ts
  apps/api/src/modules/posts/posts.controller.ts
  apps/api/src/modules/posts/posts.module.ts
  apps/api/src/modules/posts/posts.service.ts
  apps/api/src/modules/upload/cloudinary/cloudinary.service.ts
  apps/api/src/modules/upload/upload.controller.ts
  apps/api/src/modules/upload/upload.module.ts
  apps/api/src/modules/upload/upload.service.ts
  apps/db/dump-2hand_ev_battery_trading-202509300333.dump
  apps/web/package.json
  pnpm-lock.yaml
Labels: Review effort 4/5

#54 feat: enhance BaseCreatePostDto with additional properties and API documentation
  apps/api/src/modules/posts/dto/base-create-post.dto.ts
  apps/api/src/modules/posts/posts.controller.ts
Labels: Review effort 2/5
